---
title: ""
format: 
  html:
    echo: false
    message: false
    warning: false
    fig-width: 10
    fig-height: 8
    fig-align: center
    dpi: 300
editor: source
---

## **My Model vs Vegas**

```{r setup}
#| include: false

library(tidyverse)
library(nflfastR)
library(nflreadr)
library(ggimage)
# library(plotly)
# library(ggrepel)
library(patchwork)
library(caret)
# library(vip)
# library(plotly)
# library(Rcpp)
# library(RcppParallel)
library(rsample)
# library(gbm)
# library(e1071)
# library(gtsummary)

knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

# options(
#   ggplot2.continuous.colour = "viridis",
#   ggplot2.continuous.fill = "viridis"
# )
# 
# scale_colour_discrete = scale_colour_viridis_d
# scale_fill_discrete = scale_fill_viridis_d

`%nin%` = Negate(`%in%`)

set.seed(37564)

teams_colors_logos = teams_colors_logos %>% filter(team_abbr %nin% c("OAK", "SD", "STL", "LAR"))
```

```{r load data and mods}
#| include: false

# week_n = ceiling(as.integer(Sys.Date() - as.Date("2025-09-07")) / 7)
week_n = ceiling(as.integer(Sys.Date() - as.Date("2025-09-07")) / 7) + 1

# Load 2025 data
df_szn_pbp = 
  load_pbp(2025) %>%  
  filter(season_type == "REG")

df_roster = fast_scraper_roster(2025)

# Not sure what this does
# szn2025_sched = 
#   read_csv("./schedule2025.csv") %>% 
#   pivot_longer(
#     2:19,
#     values_to = "team",
#     names_to = "week"
#   ) %>% 
#   mutate(
#     TEAM = str_remove(TEAM, "@"), 
#    team = str_remove(team, "@"),
#    TEAM = str_replace(TEAM, "LAR", "LA"), 
#    team = str_replace(team, "LAR", "LA"),
#    TEAM = str_replace(TEAM, "WSH", "WAS"), 
#    team = str_replace(team, "WSH", "WAS")
#   ) %>% 
#   rename(
#     team_opp = team,
#     team = TEAM
#   ) %>% 
#   mutate(week = as.integer(week))

# Load schedules
df_schedule = 
  fast_scraper_schedules() %>% 
  filter(season == 2025) %>% 
  mutate(
    time_start = as.integer(str_remove(gametime, ":")),
    international = ifelse(location == "Neutral", 1, 0),
    enclosed_field = 
      case_when(
        roof %in% c("closed", "dome") ~ 1,
        roof %in% c("open", "outdoors") ~ 0,
        .default = NA
      ),
    turf_field = 
      case_when(
        str_detect(surface, "turf") | surface == "" | str_detect(surface, "astro") ~ 1,
        str_detect(surface, "grass") ~ 0, 
        .default = NA
      )
  )

df_weather_last = 
  readxl::read_xlsx("weather_2025_raw.xlsx", sheet = glue::glue("Week {week_n-1}")) %>% 
  mutate(across(c(temp, wind), ~ as.integer(.)))

df_weather = 
  readxl::read_xlsx("weather_2025_raw.xlsx", sheet = glue::glue("Week {week_n}")) %>% 
  mutate(across(c(temp, wind), ~ as.integer(.)))

df_lines_open = 
  readxl::read_xlsx("betting_lines_open_2025.xlsx", sheet = "Sheet1") %>% 
  mutate(
    game_id = 
      case_when(
        str_length(week) < 2 ~ str_c("2025_0", week, "_", game),
        str_length(week) == 2 ~ str_c("2025_", week, "_", game),
        .default = NA
      )
  ) %>% 
  relocate(game_id)

mod_total_team_svm = readRDS("mod_total_team_svm.rds")
mod_total_correct_enet = readRDS("mod_total_correct_enet.rds")
mod_spread_correct_enet = readRDS("mod_spread_correct_enet.rds")
df_total_team_train = readRDS("total_team_train_df.rds")
```

```{r create datasets}
#| include: false

# Make teams ID data
df_teams = 
  df_szn_pbp %>% 
  tibble() %>% 
  distinct(home_team) %>% 
  rename(team = home_team) %>% 
  arrange(team) %>% 
  rowid_to_column("team_id")

# Make divisions data:
df_division = 
  df_teams %>% 
  mutate(
    division = 
      case_match(
        team,
        c("BUF", "MIA", "NE", "NYJ") ~ "AFC East",
        c("PIT", "CIN", "BAL", "CLE") ~ "AFC North",
        c("IND", "JAX", "TEN", "HOU") ~ "AFC South",
        c("LAC", "KC", "DEN", "LV") ~ "AFC West",
        c("NYG", "DAL", "WAS", "PHI") ~ "NFC East",
        c("GB", "MIN", "CHI", "DET") ~ "NFC North",
        c("NO", "ATL", "CAR", "TB") ~ "NFC South",
        c("SF", "ARI", "SEA", "LA") ~ "NFC West"
      ),
    conf = str_extract(division, "^[A-Z]FC")
  )

df_rolling_epa = 
  df_szn_pbp %>% 
  # filter(season > 2008) %>% 
  filter(rush == 1 | pass == 1, !is.na(epa), !is.na(posteam), posteam != "") %>%
  select(season, week, posteam, pass, epa) %>% 
  group_by(season, week, posteam, pass) %>% 
  summarize(epa = mean(epa)) %>% 
  pivot_wider(names_from = pass, values_from = epa) %>% 
  rename(off_pass_epa = "1", off_rush_epa = "0", team = "posteam") %>% 
  ungroup() %>% 
  left_join(
    df_szn_pbp %>% 
      # filter(season > 2008) %>% 
      filter(rush == 1 | pass == 1, !is.na(epa), !is.na(defteam), defteam != "") %>%
      select(season, week, defteam, pass, epa) %>% 
      group_by(season, week, defteam, pass) %>% 
      summarize(epa = mean(epa)) %>% 
      pivot_wider(names_from = pass, values_from = epa) %>% 
      rename(def_pass_epa = "1", def_rush_epa = "0", team = "defteam") %>% 
      ungroup(),
    by = c("season", "week", "team")
  ) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(n_game = row_number()) %>% 
  mutate(
    # tst = cumsum(off_pass_epa),
    # avg_cum_sum = tst / n_game,
    across(ends_with("_epa"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    across(starts_with("rolling_"), ~ lag(.), .names = "prior_{col}")
  ) %>% 
  ungroup()

df_rolling_pace = 
  df_szn_pbp %>% 
  # filter(season > 2008) %>% 
  group_by(season, week, game_id, posteam) %>% 
  summarise(n_plays = n()) %>% 
  drop_na() %>% 
  rename(team = posteam) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(n_game = row_number()) %>% 
  mutate(
    rolling_pace = cumsum(n_plays) / n_game,
    across(starts_with("rolling_"), ~ lag(.), .names = "prior_{col}"),
  ) %>% 
  ungroup()

df_rolling_rz_eff =
  df_szn_pbp %>% 
  filter(season > 2008) %>% 
  group_by(season, week, game_id, posteam) %>% 
  mutate(
    redzone = 
      case_when(
        yardline_100 <= 20 & two_point_attempt == 1 ~ NA,
        yardline_100 <= 20 & extra_point_attempt == 1 ~ NA,
        yardline_100 <= 20 ~ 1,
        yardline_100 > 20 ~ 0,
        .default = NA
      )
  ) %>% 
  select(game_id, drive, posteam, yardline_100, redzone, touchdown, extra_point_attempt, two_point_attempt) %>% 
  ungroup() %>% 
  group_by(season, week, game_id, posteam, drive) %>%
  mutate(
    n_drive = row_number(),
    n_drive_rz = ifelse(redzone == 1, n_drive, NA),
    redzone_start = ifelse(n_drive_rz == min(n_drive_rz, na.rm = T), 1, 0)
  ) %>% 
  ungroup() %>% 
  group_by(season, week, game_id, posteam) %>% 
  summarise(
    redzone_trips = sum(redzone_start == 1, na.rm = T),
    redzone_tds = sum(redzone == 1 & touchdown == 1, na.rm = T)
  ) %>% 
  drop_na() %>% 
  ungroup() %>% 
  rename(team = posteam) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(
    n_game = row_number()
  ) %>% 
  mutate(
    rolling_rz_n = cumsum(redzone_trips) / n_game,
    rolling_rz_td = cumsum(redzone_tds) / n_game,
    rolling_rz_eff = 
      case_when(
        rolling_rz_n == 0 ~ 0, 
        .default = rolling_rz_td / rolling_rz_n
      ),
    across(starts_with("rolling_") & ends_with("_eff"), ~ lag(.), .names = "prior_{col}")
  ) %>% 
  ungroup()

df_rolling_success =
  df_szn_pbp %>% 
  filter(season > 2008) %>% 
  filter(down %in% c(1:4) & !is.na(yards_gained)) %>% 
  group_by(season, week, game_id, posteam) %>%
  mutate(
    success = 
      case_when(
        down == 1 & yards_gained >= 0.4 * ydstogo ~ 1,
        down == 2 & yards_gained >= 0.6 * ydstogo ~ 1,
        down %in% c(3:4) & yards_gained >= ydstogo ~ 1,
        .default = 0
      )
  ) %>%
  summarise(
    sum_success_off = sum(success, na.rm = T),
    n_success_off = n(),
    .groups = "drop"
  ) %>% 
  drop_na() %>% 
  ungroup() %>% 
  rename(team = posteam) %>% 
  left_join(
    df_szn_pbp %>% 
      filter(season > 2008) %>% 
      filter(down %in% c(1:4) & !is.na(yards_gained)) %>% 
      group_by(season, week, game_id, defteam) %>%
      mutate(
        success = 
          case_when(
            down == 1 & yards_gained >= 0.4 * ydstogo ~ 1,
            down == 2 & yards_gained >= 0.6 * ydstogo ~ 1,
            down %in% c(3:4) & yards_gained >= ydstogo ~ 1,
            .default = 0
          )
      ) %>%
      summarise(
        sum_success_def = sum(success, na.rm = T),
        n_success_def = n(),
        .groups = "drop"
      ) %>% 
      drop_na() %>% 
      ungroup() %>% 
      rename(team = defteam),
    by = c("season", "week", "game_id", "team")
  ) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(
    n_game = row_number()
  ) %>% 
  mutate(
    across(starts_with("sum_success_"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    across(starts_with("n_success_"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    # rolling_success = cumsum(sum_success) / n_game,
    # rolling_success_n = cumsum(n_success) / n_game,
    rolling_success_off_rate = rolling_sum_success_off / rolling_n_success_off,
    rolling_success_def_rate = rolling_sum_success_def / rolling_n_success_def,
    # rolling_success_def_rate = rolling_success / rolling_success_n,
    across(starts_with("rolling_") & ends_with("_rate"), ~ lag(.), .names = "prior_{col}")
  ) %>% 
  ungroup()

df_rolling_exp_plays = 
  df_szn_pbp %>% 
  filter(season > 2008) %>% 
  filter(!is.na(posteam)) %>%
  group_by(season, week, game_id, posteam) %>%
  mutate(
    explosive = ifelse(yards_gained >= 20, 1, 0)
  ) %>%
  summarise(
    n_exp_off = sum(explosive, na.rm = T),
    n_tot_off = n(),
    .groups = "drop"
  ) %>% 
  drop_na() %>% 
  ungroup() %>% 
  rename(team = posteam) %>% 
  left_join(
    df_szn_pbp %>% 
      filter(season > 2008) %>%
      filter(!is.na(defteam)) %>%
      group_by(season, week, game_id, defteam) %>%
      mutate(
        explosive = ifelse(yards_gained >= 20, 1, 0)
      ) %>%
      summarise(
        n_exp_def = sum(explosive, na.rm = T),
        n_tot_def = n(),
        .groups = "drop"
      ) %>% 
      drop_na() %>% 
      ungroup() %>% 
      rename(team = defteam),
    by = c("season", "week", "game_id", "team")
  ) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(
    n_game = row_number()
  ) %>% 
  mutate(
    across(starts_with("n_exp"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    across(starts_with("n_tot"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    # rolling_success = cumsum(sum_success) / n_game,
    # rolling_success_n = cumsum(n_success) / n_game,
    rolling_exp_off_rate = rolling_n_exp_off / rolling_n_tot_off,
    rolling_exp_def_rate = rolling_n_exp_def / rolling_n_tot_def,
    # rolling_success_def_rate = rolling_success / rolling_success_n,
    across(starts_with("rolling_") & ends_with("_rate"), ~ lag(.), .names = "prior_{col}")
  ) %>% 
  ungroup()

df_rolling_to_rate = 
  df_szn_pbp %>% 
  filter(season > 2008) %>% 
  filter(!is.na(posteam)) %>%
  group_by(season, week, game_id, posteam) %>%
  mutate(
    turnover = ifelse(interception == 1 | fumble == 1, 1, 0)
  ) %>%
  summarise(
    n_to_off = sum(turnover, na.rm = T),
    n_tot_off = n(),
    .groups = "drop"
  ) %>% 
  drop_na() %>% 
  ungroup() %>% 
  rename(team = posteam) %>% 
  left_join(
    df_szn_pbp %>% 
      filter(season > 2008) %>%
      filter(!is.na(defteam)) %>%
      group_by(season, week, game_id, defteam) %>%
      mutate(
        turnover = ifelse(interception == 1 | fumble == 1, 1, 0)
      ) %>%
      summarise(
        n_to_def = sum(turnover, na.rm = T),
        n_tot_def = n(),
        .groups = "drop"
      ) %>% 
      drop_na() %>% 
      ungroup() %>% 
      rename(team = defteam),
    by = c("season", "week", "game_id", "team")
  ) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(
    n_game = row_number()
  ) %>% 
  mutate(
    across(starts_with("n_to_"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    across(starts_with("n_tot_"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    # rolling_success = cumsum(sum_success) / n_game,
    # rolling_success_n = cumsum(n_success) / n_game,
    rolling_to_off_rate = rolling_n_to_off / rolling_n_tot_off,
    rolling_to_def_rate = rolling_n_to_def / rolling_n_tot_def,
    # rolling_success_def_rate = rolling_success / rolling_success_n,
    across(starts_with("rolling_") & ends_with("_rate"), ~ lag(.), .names = "prior_{col}")
  ) %>% 
  ungroup()

df_rolling_pen_yards = 
  df_szn_pbp %>% 
  filter(season > 2008) %>%
  filter(!is.na(posteam)) %>%
  group_by(season, week, game_id, posteam) %>%
  summarise(
    n_pen_off = sum(penalty_yards, na.rm = T),
    n_tot_off = n(),
    .groups = "drop"
  ) %>% 
  drop_na() %>% 
  ungroup() %>% 
  rename(team = posteam) %>% 
  left_join(
    df_szn_pbp %>% 
      filter(season > 2008) %>% 
      filter(!is.na(defteam)) %>%
      group_by(season, week, game_id, defteam) %>%
      summarise(
        n_pen_def = sum(penalty_yards, na.rm = T),
        n_tot_def = n(),
        .groups = "drop"
      ) %>% 
      drop_na() %>% 
      ungroup() %>% 
      rename(team = defteam),
    by = c("season", "week", "game_id", "team")
  ) %>% 
  group_by(season, team) %>% 
  arrange(season, team, week) %>% 
  mutate(
    n_game = row_number()
  ) %>% 
  mutate(
    across(starts_with("n_pen_"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    across(starts_with("n_tot_"), ~ cumsum(.) / n_game, .names = "rolling_{col}"),
    rolling_pen_yards_off = rolling_n_pen_off / rolling_n_tot_off,
    rolling_pen_yards_def = rolling_n_pen_def / rolling_n_tot_def,
    across(starts_with("rolling_") & contains("_yards_"), ~ lag(.), .names = "prior_{col}")
  ) %>% 
  ungroup()

df_qb_starters = 
  df_szn_pbp %>% 
  filter(qtr == 1) %>%
  filter(!is.na(passer_id)) %>% 
  group_by(season, week, game_id, posteam, passer_id) %>%
  summarise(dropbacks = n(), .groups = "drop_last") %>%
  slice_max(order_by = dropbacks, n = 1, with_ties = F) %>%
  ungroup() %>%
  rename(team = posteam, qb_id = passer_id)

df_qb_cont_old =
  df_szn_pbp %>%
  filter(season > 2008) %>%
  distinct(season, week, game_id, home_team, away_team, total_line, total, spread_line, result, home_score, away_score) %>%
  pivot_longer(
    ends_with("_team"),
    names_to = "home_away",
    values_to = "team"
  ) %>%
  left_join(
    df_qb_starters %>%
      select(game_id, team, qb_id),
    by = c("game_id", "team")
  ) %>%
  group_by(season, team) %>%
  arrange(week, .by_group = TRUE) %>%
  mutate(
    prev_qb = lag(qb_id),
    qb_cont = ifelse(!is.na(prev_qb) & qb_id == prev_qb, 1, 0)
  ) %>%
  ungroup() %>%
  select(season, week, team, game_id, qb_cont)

df_rest_days_old =
  df_szn_pbp %>%
  filter(season > 2008) %>%
  mutate(date_game = as.Date(game_date)) %>%
  distinct(season, week, game_id, home_team, away_team, date_game) %>%
  pivot_longer(
    ends_with("_team"),
    names_to = "home_away",
    values_to = "team"
  ) %>%
  group_by(season, team) %>%
  arrange(date_game, .by_group = TRUE) %>%
  mutate(
    prev_date_game = lag(date_game),
    rest_days = as.integer(date_game - prev_date_game)
  ) %>%
  ungroup() %>%
  select(season, week, team, game_id, rest_days)

df_stadium_coords = 
  tibble::tribble(
    ~team,    ~stadium,                        ~lat,      ~lon,
    # --- Current Teams ---
    "ARI",    "State Farm Stadium",            33.5273,  -112.2639,
    "ATL",    "Mercedes-Benz Stadium",         33.7558,   -84.4018,
    "BAL",    "M&T Bank Stadium",              39.2781,   -76.6228,
    "BUF",    "Highmark Stadium",              42.7735,   -78.7869,
    "CAR",    "Bank of America Stadium",       35.2258,   -80.8528,
    "CHI",    "Soldier Field",                 41.8625,   -87.6167,
    "CIN",    "Paycor Stadium",                39.0954,   -84.5160,
    "CLE",    "Cleveland Browns Stadium",      41.5061,   -81.6994,
    "DAL",    "AT&T Stadium",                  32.7473,   -97.0945,
    "DEN",    "Empower Field",                 39.7439,  -105.0200,
    "DET",    "Ford Field",                    42.3400,   -83.0456,
    "GB",     "Lambeau Field",                 44.5013,   -88.0622,
    "HOU",    "NRG Stadium",                   29.6849,   -95.4108,
    "IND",    "Lucas Oil Stadium",             39.7601,   -86.1638,
    "JAX",    "EverBank Stadium",              30.3239,   -81.6373,
    "KC",     "Arrowhead Stadium",             39.0489,   -94.4839,
    "LA",     "SoFi Stadium",                  33.9536,  -118.3396,
    "LAC",    "SoFi Stadium",                  33.9536,  -118.3396,
    "LV",     "Allegiant Stadium",             36.0908,  -115.1839,
    "MIA",    "Hard Rock Stadium",             25.9580,   -80.2389,
    "MIN",    "U.S. Bank Stadium",             44.9738,   -93.2581,
    "NE",     "Gillette Stadium",              42.0909,   -71.2643,
    "NO",     "Caesars Superdome",             29.9508,   -90.0811,
    "NYG",    "MetLife Stadium",               40.8135,   -74.0745,
    "NYJ",    "MetLife Stadium",               40.8135,   -74.0745,
    "PHI",    "Lincoln Financial Field",       39.9008,   -75.1675,
    "PIT",    "Acrisure Stadium",              40.4468,   -80.0158,
    "SEA",    "Lumen Field",                   47.5951,  -122.3323,
    "SF",     "Levi's Stadium",                37.4030,  -121.9700,
    "TB",     "Raymond James Stadium",         27.9758,   -82.5033,
    "TEN",    "Nissan Stadium",                36.1665,   -86.7713,
    "WAS",    "FedExField",                    38.9078,   -76.8644,
    
    # --- Old Stadiums / Relocated Teams ---
    "SD",     "Qualcomm Stadium",              32.7831,  -117.1195,  # San Diego Chargers (1967–2016)
    "STL",    "Edward Jones Dome",             38.6329,   -90.1885,  # St. Louis Rams (1995–2015)
    "OAK",    "Oakland Coliseum",              37.7516,  -122.2005,  # Oakland Raiders (1966–2019)
  
    # --- International / Neutral ---
    "INTL_LON",   "Wembley Stadium",      51.5560,   -0.2796,
    "INTL_LON",   "Tottenham Stadium",     51.6043,   -0.0664,
    "INTL_MEX",   "Azteca Stadium",  19.3029,  -99.1505,
    "INTL_GER",   "Allianz Arena",        48.2188,   11.6247,
    "INTL_GER",   "Deutsche Bank Park",50.0686,    8.6456
) %>%
  add_row(
    team = "INTL_BRA", 
    stadium = "Arena Corinthians", 
    lat = -23.5450, 
    lon = -46.4734
  ) %>%
  add_row(
    team    = "INTL_TWICKENHAM",
    stadium = "Twickenham Stadium",
    lat     = 51.4560,
    lon     = -0.3415
  ) %>%
  add_row(
    team    = "INTL_TOR",
    stadium = "Rogers Centre",
    lat     = 43.6414,
    lon     = -79.3894
  )

df_games_coords = 
  df_schedule %>% 
  rename(stadium_old = stadium) %>% 
  filter(location != "Neutral") %>% 
  left_join(
    df_stadium_coords %>% 
      rename(home_team = team),
    by = "home_team"
  ) %>% 
  rbind(
    df_schedule %>% 
      filter(location == "Neutral") %>% 
      left_join(
        df_stadium_coords %>% 
          select(-team),
        by = "stadium"
      ) %>% 
      mutate(
        lat = 
          case_when(
            is.na(lat) & game_type == "REG" ~ df_stadium_coords %>% filter(stadium == "Wembley Stadium") %>% pull(lat), 
            game_type == "REG" ~ df_stadium_coords %>% filter(stadium == "Wembley Stadium") %>% pull(lat), 
            .default = lat
          ),
        lon = 
          case_when(
            is.na(lon) & game_type == "REG" ~ df_stadium_coords %>% filter(stadium == "Wembley Stadium") %>% pull(lon), 
            game_type == "REG" ~ df_stadium_coords %>% filter(stadium == "Wembley Stadium") %>% pull(lon), 
            .default = lon
          ),
        stadium_old = NA
      )
  ) %>% 
  drop_na(lat, lon) %>% 
  rename(
    game_lat = lat,
    game_lon = lon
  ) %>% 
  select(game_id, home_team, location, stadium, game_lat, game_lon) %>% 
  distinct()

df_team_coords = 
  df_games_coords %>%
  distinct(home_team, .keep_all = TRUE) %>%
  select(-game_id) %>% 
  rename(
    team = home_team,
    home_lat = game_lat, 
    home_lon = game_lon
  )

haversine <- function(lat1, lon1, lat2, lon2) {
  R <- 6371  # km
  dlat <- (lat2 - lat1) * pi/180
  dlon <- (lon2 - lon1) * pi/180
  a <- sin(dlat/2)^2 + cos(lat1*pi/180) * cos(lat2*pi/180) * sin(dlon/2)^2
  c <- 2 * atan2(sqrt(a), sqrt(1-a))
  R * c
}

df_travel_old =
  df_szn_pbp %>% 
  distinct(season, week, game_id, home_team, away_team) %>% 
  mutate(
    home_team = 
      case_when(
        season < 2017 & home_team == "LA" ~ "STL",
        season < 2017 & home_team == "LAC" ~ "SD",
        season < 2020 & home_team == "LV" ~ "OAK",
        .default = home_team
      ),
    away_team = 
      case_when(
        season < 2017 & away_team == "LA" ~ "STL",
        season < 2017 & away_team == "LAC" ~ "SD",
        season < 2020 & away_team == "LV" ~ "OAK",
        .default = away_team
      )
  ) %>% 
  pivot_longer(
    ends_with("_team"),
    names_to = "home_away",
    values_to = "team"
  ) %>% 
  left_join(df_games_coords %>% select(game_id, location, stadium, game_lat, game_lon), by = "game_id") %>% 
  left_join(df_team_coords %>% select(-location), by = "team") %>% 
  mutate(
    travel_km = ifelse(home_away == "home" & location != "Neutral", 0, haversine(home_lat, home_lon, game_lat, game_lon)),
    team = 
      case_when(
        season < 2017 & team == "LA" ~ "STL",
        season < 2017 & team == "SD" ~ "LAC",
        season < 2020 & team == "OAK" ~ "LV",
        .default = team
      )
  ) %>% 
  select(season, week, team, game_id, travel_km)

df_team_total_spread_rolling =
  df_szn_pbp %>% 
  distinct(season, week, game_id, home_team, away_team, total_line, total, spread_line, result, home_score, away_score) %>%
  left_join(df_division %>% select(team, division) %>% rename(home_team = team, division_home = division), by = "home_team") %>%
  left_join(df_division %>% select(team, division) %>% rename(away_team = team, division_away = division), by = "away_team") %>% 
  mutate(division_game = ifelse(division_home == division_away, 1, 0)) %>%
  pivot_longer(
    ends_with("_team"),
    names_to = "home_away",
    values_to = "team"
  ) %>% 
  mutate(home_away = str_remove(home_away, "_team$")) %>% 
  left_join(df_rolling_epa, by = c("season", "week", "team")) %>% 
  left_join(df_rolling_pace %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_rolling_rz_eff %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_rolling_success %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_rolling_exp_plays %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_rolling_to_rate %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_rolling_pen_yards %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_qb_cont_old %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_rest_days_old %>% select(-game_id), by = c("season", "week", "team")) %>% 
  left_join(df_travel_old %>% select(-game_id), by = c("season", "week", "team")) %>% 
  select(season, week, game_id, team, total_line, total, spread_line, result, home_away, home_score, away_score, division_game, starts_with("prior_"), qb_cont, rest_days, travel_km) %>%
  mutate(
    travel_km = 
      case_when(
        travel_km == 0 ~ 0,
        .default = log(travel_km)
      ),
    total_team = 
      case_when(
        home_away == "home" ~ home_score,
        home_away == "away" ~ away_score,
        .default = NA
      )
  ) %>% 
  ungroup()

df_field_game = 
  df_szn_pbp %>% 
  distinct(game_id, home_team, away_team, roof, surface, wind, temp, start_time, total) %>% 
  # pull(roof) %>% table(useNA = "ifany")
  mutate(
    time_start = 
      as.integer(str_remove(str_remove(str_extract(start_time, "\\d+:\\d+:\\d+$"), ":\\d+$"), ":")),
    international = ifelse(surface == "", 1, 0),
    enclosed_field = 
      case_when(
        roof %in% c("closed", "dome") ~ 1,
        roof %in% c("open", "outdoors") ~ 0,
        .default = NA
      ),
    turf_field = 
      case_when(
        str_detect(surface, "turf") | surface == "" | str_detect(surface, "astro") ~ 1,
        str_detect(surface, "grass") ~ 0, 
        .default = NA
      ),
    wind = 
      case_when(
        is.na(wind) & enclosed_field == 1 ~ 0,
        .default = wind
      ),
    temp = 
      case_when(
        is.na(temp) & enclosed_field == 1 ~ 72,
        .default = temp
      )
  ) %>% 
  select(game_id, home_team, away_team, ends_with("_field"), international, time_start, wind, temp) %>% 
  left_join(
    df_weather_last %>% 
      separate_longer_delim(game, "vs") %>% 
      rename(
        home_team = game,
        wind_update = wind,
        temp_update = temp
      ),
    by = "home_team"
  ) %>% 
  mutate(
    temp = 
      case_when(
        is.na(temp) ~ temp_update,
        .default = temp
      ),
    wind = 
      case_when(
        is.na(wind) ~ wind_update,
        .default = wind
      )
  ) %>% 
  select(-ends_with("_update")) %>% 
  left_join(df_division %>% select(team, division) %>% rename(home_team = team, division_home = division), by = "home_team") %>%
  left_join(df_division %>% select(team, division) %>% rename(away_team = team, division_away = division), by = "away_team") %>% 
  mutate(division_game = ifelse(division_home == division_away, 1, 0))

df_field = 
  df_szn_pbp %>% 
  filter(season == 2025 & week == week_n) %>%
  distinct(game_id, roof, surface, home_team) %>% 
  group_by(home_team, roof, surface) %>%
  summarise(
    n_field = n()
  ) %>%
  ungroup() %>%
  group_by(home_team) %>% 
  arrange(home_team, -n_field) %>%
  slice(1) %>%
  rename(team = home_team) %>% 
  mutate(
    enclosed_field = 
      case_when(
        roof %in% c("closed", "dome") ~ 1,
        roof %in% c("open", "outdoors") ~ 0,
        .default = NA
      ),
    turf_field = 
      case_when(
        str_detect(surface, "turf") | surface == "" | str_detect(surface, "astro") ~ 1,
        str_detect(surface, "grass") ~ 0, 
        .default = NA
      )
  ) %>% 
  select(team, enclosed_field, turf_field)

df_qb_cont =
  tibble(
    team = df_teams$team,
    qb_cont = 1
  ) %>% 
  rows_update(
    tibble(
      team = c("NYG"),
      qb_cont = 0
    ),
    by = "team"
  )

df_rest_days =
  df_schedule %>% 
  filter(season == 2025 & week == week_n) %>% 
  select(home_team, away_team, home_rest, away_rest) %>% 
  pivot_longer(
    c(home_team, away_team),
    names_to = "home_away",
    values_to = "team"
  ) %>% 
  pivot_longer(
    c(home_rest, away_rest),
    names_to = "home_away_rest",
    values_to = "rest_days"
  ) %>% 
  filter(str_extract(home_away, "^[a-z]+") == str_extract(home_away_rest, "^[a-z]+")) %>% 
  select(team, rest_days)

df_travel = 
  df_games_coords %>% 
  filter(str_detect(game_id, glue::glue("^2025_{week_n}_"))) %>% 
  mutate(away_team = str_extract(str_remove(game_id, "^2025_10_"), "[A-Z]+")) %>% 
  pivot_longer(
    c(home_team, away_team),
    names_to = "home_away",
    values_to = "team"
  ) %>% 
  left_join(df_team_coords %>% select(team, home_lat, home_lon), by = "team") %>% 
  mutate(
    travel_km = ifelse(home_away == "home" & location != "Neutral", 0, haversine(home_lat, home_lon, game_lat, game_lon))
  ) %>% 
  select(team, travel_km)

df_total_team_test_solo =
  df_schedule %>% 
  filter(week == week_n) %>% 
  select(game_id, week, home_team, away_team) %>% 
  pivot_longer(
    c(home_team, away_team),
    names_to = "home_away",
    values_to = "team"
  ) %>% 
  group_by(game_id) %>% 
  mutate(
    home_away = str_remove(home_away, "_team$"),
    team_opp = 
      case_when(
        row_number() == 1 ~ lead(team),
        row_number() == 2 ~ lag(team),
        .default = NA
      ),
    team_home = 
      case_when(
        home_away == "home" ~ team,
        .default = NA
      )
  ) %>% 
  ungroup() %>% 
  select(-game_id) %>% 
  left_join(df_division %>% select(team, division), by = "team") %>% 
  left_join(df_division %>% select(team, division) %>% rename(team_opp = team, division_opp = division), by = "team_opp") %>% 
  mutate(division_game = ifelse(division == division_opp, 1, 0)) %>% 
  left_join(
    df_rolling_epa %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, starts_with("rolling_")),
    by = c("team")
  ) %>% 
  left_join(
    df_rolling_pace %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, starts_with("rolling_")),
    by = c("team")
  ) %>% 
  left_join(
    df_rolling_rz_eff %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, rolling_rz_eff),
    by = c("team")
  ) %>% 
  left_join(
    df_rolling_success %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, rolling_success_off_rate, rolling_success_def_rate),
    by = c("team")
  ) %>% 
  left_join(
    df_rolling_exp_plays %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, rolling_exp_off_rate, rolling_exp_def_rate),
    by = c("team")
  ) %>% 
  left_join(
    df_rolling_to_rate %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, rolling_to_off_rate, rolling_to_def_rate),
    by = c("team")
  ) %>% 
  left_join(
    df_rolling_pen_yards %>% 
      group_by(season, team) %>% 
      filter(season == 2025 & week == max(week, na.rm = T)) %>% 
      ungroup() %>% 
      select(team, rolling_pen_yards_off, rolling_pen_yards_def),
    by = c("team")
  ) %>% 
  left_join(
    df_qb_cont %>%
      select(team, qb_cont),
    by = c("team")
  ) %>%
  left_join(
    df_rest_days %>%
      select(team, rest_days),
    by = c("team")
  ) %>% 
  left_join(
    df_travel %>%
      select(team, travel_km),
    by = c("team")
  ) %>% 
  rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
  mutate(
    across(ends_with("_field"), ~ case_when(home_away == "home" ~ ., .default = NA)),
    travel_km = 
      case_when(
        travel_km == 0 ~ 0,
        .default = log(travel_km)
      )
  )

df_total_team_test = 
  df_total_team_test_solo %>% 
  distinct() %>% 
  left_join(
    df_total_team_test_solo %>% 
      distinct() %>% 
      select(team_opp, starts_with("prior_"), qb_cont, rest_days, travel_km) %>% 
      rename_with(~ str_c(., "_opp"), everything() & -c(team_opp)) %>% 
      rename(team = team_opp),
    by = "team"
  )

df_pred_total_spread = 
  df_total_team_test %>% 
  drop_na(rest_days, prior_rolling_off_rush_epa, prior_rolling_off_rush_epa_opp) %>% 
  mutate(
    pred_total_team_svm = predict(mod_total_team_svm, newdata = .)
  ) %>% 
  relocate(pred_total_team_svm, .after = team) %>% 
  left_join(
    df_total_team_test %>% 
      drop_na(rest_days, prior_rolling_off_rush_epa, prior_rolling_off_rush_epa_opp) %>% 
      mutate(
        pred_total_team_svm = predict(mod_total_team_svm, newdata = .)
      ) %>% 
      select(team, pred_total_team_svm) %>% 
      rename(
        pred_total_team_opp_svm = pred_total_team_svm,
        team_opp = team
      ),
    by = "team_opp"
  ) %>% 
  mutate(
    total_game = pred_total_team_svm + pred_total_team_opp_svm,
    spread_game = 
      case_when(
        home_away == "home" ~ pred_total_team_svm - pred_total_team_opp_svm,
        home_away == "away" ~ pred_total_team_opp_svm - pred_total_team_svm,
        .default = NA
      )
  ) %>% 
  pivot_wider(
    id_cols = c(week, team, team_opp, team_home, total_game, spread_game),
    names_from = home_away,
    values_from = starts_with("prior_")
  ) %>% 
  mutate(game = str_c(team, "vs", team_opp)) %>% 
  pivot_longer(
    c(team, team_opp),
    names_to = "team_game",
    values_to = "team"
  ) %>%
  arrange(team, team_game) %>%
  relocate(game, team, team_game, team_home) %>%
  group_by(team) %>%
  fill(starts_with("prior_"), .direction = "downup") %>%
  ungroup() %>% 
  select(-c(team, team_game)) %>% 
  distinct() %>%
  rowid_to_column("game_id") %>% 
  filter(str_detect(as.character(game_id / 2), "\\.5")) %>% 
  mutate(
    team_home = 
      case_when(
        is.na(team_home) ~ str_extract(game, "[A-Z]+$"),
        .default = team_home
      ),
    spread_label = 
      case_when(
        spread_game < 0 ~ str_c(team_home, " +", -round(spread_game, 1)),
        spread_game >= 0 ~ str_c(team_home, " ", -round(spread_game, 1))
      )
  ) %>% 
  relocate(spread_label, .after = spread_game)

df_pred_total_spread_adj = 
  df_pred_total_spread %>% 
  left_join(
    df_schedule %>% 
      filter(week == week_n) %>% 
      select(home_team, away_team, ends_with("_field")) %>% 
      rename(
        team_home = home_team,
        team_away = away_team
      ), 
    by = "team_home"
  ) %>% 
  left_join(df_weather, by = "game") %>%  
  mutate(
    wind = 
      case_when(
        enclosed_field == 1 ~ 0,
        .default = wind
      ),
    temp = 
      case_when(
        enclosed_field == 1 ~ 72,
        .default = temp
      )
  ) %>% 
  left_join(df_division %>% select(team, division) %>% rename(team_home = team), by = "team_home") %>% 
  left_join(df_division %>% select(team, division) %>% rename(team_away = team, division_opp = division), by = "team_away") %>% 
  mutate(division_game = ifelse(division == division_opp, 1, 0)) %>%
  mutate(
    total_adjust = predict(mod_total_correct_enet, newdata = .),
    total_game_adj = total_game + total_adjust,
    spread_adjust = predict(mod_spread_correct_enet, newdata = .),
    spread_game_adj = spread_game + spread_adjust,
    spread_adj_label = 
      case_when(
        spread_game_adj < 0 ~ str_c(team_home, " +", -round(spread_game_adj, 1)),
        spread_game_adj >= 0 ~ str_c(team_home, " ", -round(spread_game_adj, 1))
      )
  ) %>%
  relocate(total_adjust, total_game_adj, .after = total_game) %>%
  relocate(spread_game, spread_adjust, spread_game_adj, spread_adj_label, .after = total_game_adj)

# set.seed(37564)
# boot_splits_total = bootstraps(df_total_team_train, times = 100)
# 
# # 2. Predict for each bootstrap model
# boot_preds_total = map(boot_splits_total$splits, ~ {
#   train_data = analysis(.x)
# 
#   # Train SVM model
#   svm_model = train(
#     total_team ~ .,
#     data = train_data,
#     method = "svmRadial",
#     trControl = trainControl(method = "none"),  # already tuned
#     tuneGrid = tibble(
#       sigma = mod_total_team_svm$bestTune[[1]],
#       C = mod_total_team_svm$bestTune[[2]]
#     )
#   )
# 
#   # Predict on the fixed test set
#   predict(svm_model, newdata = df_total_team_test)
# })
# 
# # 3. Combine predictions into a matrix
# pred_matrix_total = do.call(cbind, boot_preds_total)
# 
# # 4. Compute mean prediction and 95% prediction interval
# df_total_team_pred_bands =
#   df_total_team_test %>%
#   drop_na(division_game) %>%
#   select(week, team, team_opp) %>%
#   mutate(
#     pred_mean  = round(rowMeans(pred_matrix_total), 2),
#     pred_lower = round(apply(pred_matrix_total, 1, quantile, probs = 0.1), 2),
#     pred_upper = round(apply(pred_matrix_total, 1, quantile, probs = 0.9), 2),
#   )
# 
# saveRDS(df_total_team_pred_bands, glue::glue("df_total_team_pred_bands_week_{week_n}.rds"))

df_total_team_pred_bands_last = readRDS(glue::glue("df_total_team_pred_bands_week_{week_n-1}.rds"))

df_total_team_pred_bands = readRDS(glue::glue("df_total_team_pred_bands_week_{week_n}.rds"))

df_spread_total_bands = 
  df_total_team_pred_bands %>% 
  left_join(
    df_total_team_pred_bands %>% 
      select(team, pred_lower, pred_upper) %>% 
      rename_with(~ str_c(., "_opp"), everything()),
    by = "team_opp"
  ) %>% 
  mutate(
    total_game_lower = pred_lower + pred_lower_opp,
    total_game_upper = pred_upper + pred_upper_opp,
    spread_lower = pred_lower - pred_upper_opp,
    spread_upper = pred_upper - pred_lower_opp
  )

df_pred_total_spread_fin = 
  df_pred_total_spread_adj %>% 
  left_join(df_spread_total_bands %>% select(team, total_game_lower, total_game_upper, spread_lower, spread_upper) %>% rename(team_home = team), by = "team_home") %>% 
  mutate(
    total_game_lower_adj = total_game_lower + total_adjust,
    total_game_upper_adj = total_game_upper + total_adjust,
    spread_lower_adj = spread_lower + spread_adjust,
    spread_upper_adj = spread_upper + spread_adjust,
    total_adj_label = round(total_game_adj, 1),
    lower_spread_adj_label = 
      case_when(
        spread_lower_adj < 0 ~ str_c(team_home, " +", -round(spread_lower_adj, 1)),
        spread_lower_adj >= 0 ~ str_c(team_home, " ", -round(spread_lower_adj, 1))
      ),
    upper_spread_adj_label = 
      case_when(
        spread_upper_adj < 0 ~ str_c(team_home, " +", -round(spread_upper_adj, 1)),
        spread_upper_adj >= 0 ~ str_c(team_home, " ", -round(spread_upper_adj, 1))
      ),
    spread_band_adj_label = 
      str_c(spread_adj_label, " (", str_remove(lower_spread_adj_label, "[A-Z]+ "), " to ", str_remove(upper_spread_adj_label, "[A-Z]+ "), ")")
  ) %>% 
  relocate(total_adj_label, spread_band_adj_label, lower_spread_adj_label, upper_spread_adj_label, total_game_lower_adj, total_game_upper_adj, spread_lower_adj, spread_upper_adj, .after = spread_label)

df_total_team_test_solo_boot_prior =
  df_schedule %>% 
  # filter(week == week_n) %>% 
  select(game_id, week, home_team, away_team) %>% 
  pivot_longer(
    c(home_team, away_team),
    names_to = "home_away",
    values_to = "team"
  ) %>% 
  group_by(game_id) %>% 
  mutate(
    home_away = str_remove(home_away, "_team$"),
    team_opp = 
      case_when(
        row_number() == 1 ~ lead(team),
        row_number() == 2 ~ lag(team),
        .default = NA
      ),
    team_home = 
      case_when(
        home_away == "home" ~ team,
        .default = NA
      )
  ) %>% 
  ungroup() %>% 
  # select(-game_id) %>% 
  left_join(df_division %>% select(team, division), by = "team") %>% 
  left_join(df_division %>% select(team, division) %>% rename(team_opp = team, division_opp = division), by = "team_opp") %>% 
  mutate(
    division_game = ifelse(division == division_opp, 1, 0)#,
    # week = week - 1
  ) %>% 
  left_join(
    df_rolling_epa %>% 
      group_by(season, team, week) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, starts_with("rolling_")) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_rolling_pace %>% 
      group_by(season, team, week) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, starts_with("rolling_")) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_rolling_rz_eff %>% 
      group_by(season, team, week) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, rolling_rz_eff) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_rolling_success %>% 
      group_by(season, team, week) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, rolling_success_off_rate, rolling_success_def_rate) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_rolling_exp_plays %>% 
      group_by(season, team, week) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, rolling_exp_off_rate, rolling_exp_def_rate) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_rolling_to_rate %>% 
      group_by(season, team, week) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, rolling_to_off_rate, rolling_to_def_rate) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_rolling_pen_yards %>% 
      group_by(season, team) %>% 
      filter(season == 2025) %>% 
      ungroup() %>% 
      select(team, week, rolling_pen_yards_off, rolling_pen_yards_def) %>% 
      rename_with(~ str_c("prior_", .), starts_with("rolling_")) %>% 
      group_by(team) %>% 
      mutate(across(starts_with("prior_"), ~ lag(.))) %>% 
      ungroup(),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_qb_cont_old %>% 
      select(team, week, qb_cont),
    by = c("team", "week")
  ) %>%
  left_join(
    df_rest_days_old %>% 
      select(team, week, rest_days),
    by = c("team", "week")
  ) %>% 
  left_join(
    df_travel_old %>% 
      select(team, week, travel_km),
    by = c("team", "week")
  ) %>% 
  mutate(
    across(ends_with("_field"), ~ case_when(home_away == "home" ~ ., .default = NA)),
    travel_km = 
      case_when(
        travel_km == 0 ~ 0,
        .default = log(travel_km)
      )
  ) %>% 
  filter(between(week, 2, week_n - 1))

df_total_team_test_boot_prior = 
  df_total_team_test_solo_boot_prior %>% 
  distinct() %>% 
  left_join(
    df_total_team_test_solo_boot_prior %>% 
      distinct() %>% 
      select(game_id, week, team_opp, starts_with("prior_"), qb_cont, rest_days, travel_km) %>% 
      rename_with(~ str_c(., "_opp"), everything() & -c(team_opp, week)) %>% 
      rename(team = team_opp),
    by = c("team", "week")
  )

# set.seed(37564)
# boot_splits_total_prior = bootstraps(df_total_team_train, times = 100)
# 
# # 2. Predict for each bootstrap model
# boot_preds_total_prior = map(boot_splits_total_prior$splits, ~ {
#   train_data = analysis(.x)
# 
#   # Train SVM model
#   svm_model = train(
#     total_team ~ .,
#     data = train_data,
#     method = "svmRadial",
#     trControl = trainControl(method = "none"),  # already tuned
#     tuneGrid = tibble(
#       sigma = mod_total_team_svm$bestTune[[1]],
#       C = mod_total_team_svm$bestTune[[2]]
#     )
#   )
# 
#   # Predict on the fixed test set
#   predict(svm_model, newdata = df_total_team_test_boot_prior)
# })
# 
# # 3. Combine predictions into a matrix
# pred_matrix_total_prior = do.call(cbind, boot_preds_total_prior)
# 
# # 4. Compute mean prediction and 95% prediction interval
# df_total_team_pred_bands_prior =
#   df_total_team_test_boot_prior %>%
#   drop_na(division_game) %>%
#   select(week, team, team_opp) %>%
#   mutate(
#     pred_mean  = round(rowMeans(pred_matrix_total_prior), 2),
#     pred_lower = round(apply(pred_matrix_total_prior, 1, quantile, probs = 0.1), 2),
#     pred_upper = round(apply(pred_matrix_total_prior, 1, quantile, probs = 0.9), 2),
#   )
# 
# saveRDS(df_total_team_pred_bands_prior, glue::glue("df_total_team_pred_bands_prior_week_{week_n}.rds"))

df_total_team_pred_bands_prior = readRDS(glue::glue("df_total_team_pred_bands_prior_week_{week_n-1}.rds")) %>% 
  rbind(df_total_team_pred_bands_last)

df_spread_total_bands_prior = 
  df_total_team_pred_bands_prior %>% 
  left_join(
    df_total_team_pred_bands_prior %>% 
      select(week, team, pred_lower, pred_upper) %>% 
      rename_with(~ str_c(., "_opp"), c(everything() & -week)),
    by = c("team_opp", "week")
  ) %>% 
  mutate(
    total_game_lower = pred_lower + pred_lower_opp,
    total_game_upper = pred_upper + pred_upper_opp,
    spread_lower = pred_lower - pred_upper_opp,
    spread_upper = pred_upper - pred_lower_opp
  )
```

::: panel-tabset

### **NFL Game Totals & Spreads**

```{r tots spreads plot}
df_pred_total_spread_fin %>% 
  left_join(
    df_schedule %>% 
      filter(week == week_n) %>% 
      select(game_id, spread_line, total_line) %>% 
      mutate(
        team_home = str_extract(game_id, "[A-Z]+$"),
        spread_line_label = 
          case_when(
            spread_line < 0 ~ str_c("(", team_home, " +", as.character(-spread_line), ")"),
            spread_line >= 0 ~ str_c("(", team_home, " ", as.character(-spread_line), ")"),
            .default = NA
          ),
        total_line_label = total_line
      ),
    by = "team_home"
  ) %>% 
  mutate(
    ind_total_hit = 
      case_when(
        total_line > total_game_upper_adj ~ 1,
        total_line < total_game_lower_adj ~ 1,
        .default = 0
      ),
    ind_spread_hit = 
      case_when(
        spread_line > spread_upper_adj ~ 1,
        spread_line < spread_lower_adj ~ 1,
        .default = 0
      )
  ) %>% 
  ggplot(aes(x = total_game_adj, y = reorder(game, total_game_adj))) +
  geom_errorbarh(aes(xmin = total_game_lower_adj, xmax = total_game_upper_adj), height = rel(0.8)) +
  geom_point(size = rel(2)) +
  geom_point(aes(color = as.factor(ind_total_hit), x = total_line, y = reorder(game, total_game_adj)), size = rel(2)) +
  geom_text(aes(label = total_adj_label, x = total_game_adj), vjust = -1, size = rel(2)) +
  geom_text(aes(label = spread_band_adj_label, x = total_game_upper_adj + 0.15), hjust = 0, size = rel(2)) +
  geom_text(aes(label = game, x = total_game_lower_adj - 1.3), hjust = 0, size = rel(2)) +
  geom_text(aes(color = as.factor(ind_total_hit), label = total_line_label, x = total_line), vjust = -1, size = rel(2)) +
  geom_text(aes(color = as.factor(ind_spread_hit), label = spread_line_label, x = total_line), vjust = 2, size = rel(1.5)) +
  # scale_color_identity() + 
  scale_x_continuous(breaks = seq(0, 100, by = 1)) +
  scale_color_manual(values = c("coral3", "skyblue2")) + 
  labs(
    x = "Predicted Total",
    y = NULL,
    title = glue::glue("Week {week_n} Spreads & Totals (80% Confidence Bands)")
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position = "none"
  ) +
  coord_cartesian(
    clip = "off",
    xlim = c(34.5, 54.5)
  )

```

### **Projected Team Scores**

```{r team scores}
df_pred_total_spread_fin %>% 
  left_join(
    df_schedule %>% 
      filter(week == week_n) %>% 
      select(game_id, spread_line, total_line) %>% 
      mutate(team_home = str_extract(game_id, "[A-Z]+$")),
    by = "team_home"
  ) %>% 
  select(game, team_home, team_away, spread_game_adj, total_game_adj, spread_line, total_line) %>% 
  pivot_longer(
    c(team_home, team_away),
    names_to = "home_away",
    names_prefix = "team_",
    values_to = "team"
  ) %>% 
  left_join(
    teams_colors_logos %>% 
      rename(team = team_abbr) %>% 
      select(team, team_color, team_logo_espn), 
    by = "team"
  ) %>% 
  group_by(game) %>% 
  mutate(
    team_points_mod = 
      case_when(
        home_away == "home" ~ round(total_game_adj / 2 + spread_game_adj / 2, 2),
        home_away == "away" ~ round(total_game_adj / 2 - spread_game_adj / 2, 2),
        .default = NA
      ),
    team_points_vegas = 
      case_when(
        home_away == "home" ~ total_line / 2 + spread_line / 2,
        home_away == "away" ~ total_line / 2 - spread_line / 2,
        .default = NA
      ),
    team_points_diff = team_points_mod - team_points_vegas,
    team = fct_reorder(factor(team), game),
    points_text_label_position = 
      case_when(
        team_points_diff >= 0 ~ team_points_diff + 0.4,
        team_points_diff < 0 ~ team_points_diff - 0.4,
        .default = NA
      ),
    points_text_label = str_c("(", round(team_points_mod, 1), "-", team_points_vegas, ")")
  ) %>% 
  ggplot(
    aes(
      x = team_points_diff, 
      y = team, 
      fill = team_color
    )
  ) + 
  geom_col(alpha = 0.85) +
  geom_image(aes(image = team_logo_espn)) +
  geom_text(aes(color = team_color, label = points_text_label, x = points_text_label_position), size = rel(2)) +
  scale_x_continuous(breaks = seq(-10, 10, by = 1)) + 
  scale_fill_identity() + 
  scale_color_identity() + 
  coord_cartesian(xlim = c(-5.5, 5.5)) +
  labs(
    title = glue::glue("Week {week_n} Model vs Vegas Projected Team Totals"),
    x = "\U0394 Team Total Points",
    y = ""
  ) +
  theme_classic() + 
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )

df_team_points_delta_szn = 
  df_total_team_test_solo_boot_prior %>% 
  left_join(
    df_total_team_test_solo_boot_prior %>% 
      group_by(game_id) %>% 
      mutate(
        team_opp = 
          case_when(
            row_number() == 1 ~ lead(team),
            row_number() == 2 ~ lag(team),
            .default = NA
          )
      ) %>% 
      relocate(team_opp, .after = team) %>% 
      ungroup() %>% 
      select(game_id, week, team_opp, starts_with("prior_"), qb_cont, rest_days, travel_km) %>% 
      rename_with(~ str_c(., "_opp"), everything() & -c(game_id, team_opp, week)) %>% 
      rename(team = team_opp),
    by = c("game_id", "team", "week")
  ) %>% 
  left_join(df_total_team_pred_bands_prior, by = c("week", "team")) %>%
  left_join(df_team_total_spread_rolling %>% select(game_id, week, team, total_team), by = c("week", "team", "game_id")) %>% 
  select(week, game_id, total_team, starts_with("prior_"), qb_cont, qb_cont_opp, rest_days, rest_days_opp, travel_km, travel_km_opp, pred_upper, pred_lower) %>% 
  drop_na() %>% 
  mutate(
    pred_total_team = predict(mod_total_team_svm, newdata = .)
  ) %>% 
  group_by(game_id) %>% 
  summarise(
    pred_total = sum(pred_total_team),
    pred_total_upper = sum(pred_upper),
    pred_total_lower = sum(pred_lower),
    actual_total = sum(total_team)
  ) %>% 
  left_join(df_field_game, by = c("game_id")) %>% 
  select(game_id, ends_with("_field"), division_game, international, wind, temp, actual_total, pred_total, pred_total_upper, pred_total_lower) %>% 
  drop_na() %>% 
  mutate(
    pred_total_adj = predict(mod_total_correct_enet, newdata = .),
    total_game_adj = pred_total + pred_total_adj
  ) %>% 
  left_join(df_lines_open %>% select(game_id, total_line), by = "game_id") %>% 
  # left_join(df_szn_pbp %>% distinct(game_id, total_line), by = "game_id") %>% 
  select(game_id, total_game_adj, total_line) %>% 
  left_join(
    df_total_team_test_solo_boot_prior %>% 
      left_join(
        df_total_team_test_solo_boot_prior %>% 
          group_by(game_id) %>% 
          mutate(
            team_opp = 
              case_when(
                row_number() == 1 ~ lead(team),
                row_number() == 2 ~ lag(team),
                .default = NA
              )
          ) %>% 
          relocate(team_opp, .after = team) %>% 
          ungroup() %>% 
          select(game_id, week, team_opp, starts_with("prior_"), qb_cont, rest_days, travel_km) %>% 
          rename_with(~ str_c(., "_opp"), everything() & -c(game_id, team_opp, week)) %>% 
          rename(team = team_opp),
        by = c("game_id", "team", "week")
      ) %>% 
      left_join(df_total_team_pred_bands_prior, by = c("week", "team")) %>%
      left_join(df_team_total_spread_rolling %>% select(game_id, week, team, total_team), by = c("week", "team", "game_id")) %>% 
      select(week, game_id, total_team, starts_with("prior_"), qb_cont, qb_cont_opp, rest_days, rest_days_opp, travel_km, travel_km_opp, pred_upper, pred_lower) %>% 
      drop_na() %>% 
      mutate(
        pred_total_team = predict(mod_total_team_svm, newdata = .)
      ) %>% 
      group_by(game_id) %>% 
      summarise(
        pred_spread = pred_total_team - lead(pred_total_team),
        pred_spread_upper = pred_upper - lead(pred_lower),
        pred_spread_lower = pred_lower - lead(pred_upper),
        actual_spread = total_team - lead(total_team)
      ) %>% 
      left_join(df_field_game, by = c("game_id")) %>% 
      select(game_id, ends_with("_field"), division_game, wind, temp, actual_spread, pred_spread, pred_spread_upper, pred_spread_lower) %>% 
      drop_na() %>% 
      ungroup() %>% 
      mutate(
        pred_spread_adj = predict(mod_spread_correct_enet, newdata = .),
        spread_game_adj = pred_spread + pred_spread_adj
      ) %>% 
      left_join(df_lines_open %>% select(game_id, spread_line), by = "game_id") %>% 
      # left_join(df_szn_pbp %>% distinct(game_id, spread_line), by = "game_id") %>% 
      select(game_id, spread_game_adj, spread_line),
    by = "game_id"
  ) %>% 
  mutate(
    week = as.integer(str_remove(str_extract(game_id, "^2025_[0-9]+"), "^2025_")), 
    team_home = str_extract(game_id, "[A-Z]+$"),
    team_away = str_extract(str_remove(game_id, "_[A-Z]+$"), "[A-Z]+$")
  ) %>% 
  select(game_id, week, team_home, team_away, spread_game_adj, total_game_adj, spread_line, total_line) %>% 
  pivot_longer(
    c(team_home, team_away),
    names_to = "home_away",
    names_prefix = "team_",
    values_to = "team"
  ) %>% 
  left_join(
    teams_colors_logos %>% 
      rename(team = team_abbr) %>% 
      select(team, team_color, team_logo_espn), 
    by = "team"
  ) %>% 
  group_by(game_id) %>% 
  mutate(
    team_points_mod = 
      case_when(
        home_away == "home" ~ round(total_game_adj / 2 + spread_game_adj / 2, 2),
        home_away == "away" ~ round(total_game_adj / 2 - spread_game_adj / 2, 2),
        .default = NA
      ),
    team_points_vegas = 
      case_when(
        home_away == "home" ~ total_line / 2 + spread_line / 2,
        home_away == "away" ~ total_line / 2 - spread_line / 2,
        .default = NA
      ),
    team_points_diff = team_points_mod - team_points_vegas
  ) %>% 
  left_join(df_team_total_spread_rolling %>% select(game_id, team, total_team), by = c("game_id", "team")) %>% 
  mutate(
    team_points_diff_actual = team_points_mod - total_team,
    team_points_diff_vegas = team_points_vegas - total_team,
  ) %>% 
  ungroup() %>% 
  group_by(team) %>% 
  mutate(
    mean_team_points_diff_vegas = mean(team_points_diff_vegas),
    mean_team_points_diff_actual = mean(team_points_diff_actual),
    mean_team_points_diff = mean(team_points_diff),
    points_text_label_position_vegas = 
      case_when(
        mean_team_points_diff_vegas >= 0 ~ mean_team_points_diff_vegas + 0.64,
        mean_team_points_diff_vegas < 0 ~ mean_team_points_diff_vegas - 0.64,
        .default = NA
      ),
    points_text_label_vegas = str_c("\U0394=", round(mean_team_points_diff_vegas, 1)),
    points_text_label_position_actual = 
      case_when(
        mean_team_points_diff_actual >= 0 ~ mean_team_points_diff_actual + 0.64,
        mean_team_points_diff_actual < 0 ~ mean_team_points_diff_actual - 0.64,
        .default = NA
      ),
    points_text_label_actual = str_c("\U0394=", round(mean_team_points_diff_actual, 1)),
    points_text_label_position = 
      case_when(
        mean_team_points_diff >= 0 ~ mean_team_points_diff + 0.33,
        mean_team_points_diff < 0 ~ mean_team_points_diff - 0.33,
        .default = NA
      ),
    points_text_label = str_c("\U0394=", round(mean_team_points_diff, 1))
  ) %>% 
  ungroup() %>% 
  distinct(team, mean_team_points_diff, mean_team_points_diff_actual, mean_team_points_diff_vegas, points_text_label_position, points_text_label, points_text_label_position_actual, points_text_label_actual, points_text_label_position_vegas, points_text_label_vegas, team_color, team_logo_espn)

df_team_points_delta_szn %>% 
  mutate(team = fct_reorder(factor(team), mean_team_points_diff)) %>% 
  ggplot(
    aes(
      x = mean_team_points_diff, 
      y = team, 
      fill = team_color
    )
  ) + 
  geom_col(alpha = 0.85) +
  geom_image(aes(image = team_logo_espn)) +
  geom_text(aes(color = team_color, label = points_text_label, x = points_text_label_position), size = rel(2.4)) +
  scale_x_continuous(breaks = seq(-10, 10, by = 1)) + 
  scale_fill_identity() + 
  scale_color_identity() + 
  coord_cartesian(xlim = c(-5.5, 5.5)) +
  labs(
    title = "Season-Long Model vs Vegas Projected Team Totals",
    x = "Mean \U0394 Team Points",
    y = ""
  ) +
  theme_classic() + 
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )

df_team_points_delta_szn %>% 
  mutate(team = fct_reorder(factor(team), mean_team_points_diff_actual)) %>% 
  ggplot(
    aes(
      x = mean_team_points_diff_actual, 
      y = team, 
      fill = team_color
    )
  ) + 
  geom_col(alpha = 0.85) +
  geom_image(aes(image = team_logo_espn)) +
  geom_text(aes(color = team_color, label = points_text_label_actual, x = points_text_label_position_actual), size = rel(2.4)) +
  scale_x_continuous(breaks = seq(-10, 10, by = 1)) + 
  scale_fill_identity() + 
  scale_color_identity() + 
  coord_cartesian(xlim = c(-8.5, 8.5)) +
  labs(
    title = "Season-Long Model vs Actual Team Totals",
    x = "Mean \U0394 Team Points",
    y = ""
  ) +
  theme_classic() + 
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(hjust = 0.5)
  )

# df_team_points_delta_szn %>% 
#   mutate(team = fct_reorder(factor(team), mean_team_points_diff_vegas)) %>% 
#   ggplot(
#     aes(
#       x = mean_team_points_diff_vegas, 
#       y = team, 
#       fill = team_color
#     )
#   ) + 
#   geom_col(alpha = 0.85) +
#   geom_image(aes(image = team_logo_espn)) +
#   geom_text(aes(color = team_color, label = points_text_label_vegas, x = points_text_label_position_vegas), size = rel(2.4)) +
#   scale_x_continuous(breaks = seq(-10, 10, by = 1)) + 
#   scale_fill_identity() + 
#   scale_color_identity() + 
#   coord_cartesian(xlim = c(-8.5, 8.5)) +
#   labs(
#     title = "Season-Long Model vs Actual Team Totals",
#     x = "Mean \U0394 Team Points",
#     y = ""
#   ) +
#   theme_classic() + 
#   theme(
#     axis.text.y = element_blank(),
#     axis.ticks.y = element_blank(),
#     axis.line.y = element_blank(),
#     plot.title = element_text(hjust = 0.5)
#   )


# plot_team_points %>% 
#   ggplotly(tooltip = "text")
```

### **Hit Rates**

```{r hit rate}
df_totals_hit_rate =
  df_total_team_test_solo_boot_prior %>% 
  left_join(
    df_total_team_test_solo_boot_prior %>% 
      group_by(game_id) %>% 
      mutate(
        team_opp = 
          case_when(
            row_number() == 1 ~ lead(team),
            row_number() == 2 ~ lag(team),
            .default = NA
          )
      ) %>% 
      relocate(team_opp, .after = team) %>% 
      ungroup() %>% 
      select(game_id, week, team_opp, starts_with("prior_"), qb_cont, rest_days, travel_km) %>% 
      rename_with(~ str_c(., "_opp"), everything() & -c(game_id, team_opp, week)) %>% 
      rename(team = team_opp),
    by = c("game_id", "team", "week")
  ) %>% 
  left_join(df_total_team_pred_bands_prior, by = c("week", "team")) %>%
  left_join(df_team_total_spread_rolling %>% select(game_id, week, team, total_team), by = c("week", "team", "game_id")) %>% 
  select(week, game_id, total_team, starts_with("prior_"), qb_cont, qb_cont_opp, rest_days, rest_days_opp, travel_km, travel_km_opp, pred_upper, pred_lower) %>% 
  drop_na() %>% 
  mutate(
    pred_total_team = predict(mod_total_team_svm, newdata = .)
  ) %>% 
  group_by(game_id) %>% 
  summarise(
    pred_total = sum(pred_total_team),
    pred_total_upper = sum(pred_upper),
    pred_total_lower = sum(pred_lower),
    actual_total = sum(total_team)
  ) %>% 
  left_join(df_field_game, by = c("game_id")) %>% 
  select(game_id, ends_with("_field"), division_game, international, wind, temp, actual_total, pred_total, pred_total_upper, pred_total_lower) %>% 
  drop_na() %>% 
  mutate(
    pred_total_adj = predict(mod_total_correct_enet, newdata = .)
  ) %>% 
  # left_join(df_szn_pbp %>% distinct(game_id, total_line), by = "game_id") %>% 
  left_join(df_lines_open %>% distinct(game_id, total_line), by = "game_id") %>% 
  mutate(
    across(c(pred_total, pred_total_upper, pred_total_lower), ~ . + pred_total_adj, .names = "{col}_adj"),
    ind_total_hit = 
      case_when(
        total_line > pred_total_upper_adj ~ "Bet Under",
        total_line < pred_total_lower_adj ~ "Bet Over",
        .default = "No Bet"
      )
  ) %>% 
  filter(ind_total_hit != "No Bet") %>% 
  mutate(
    ind_bet_hit = 
      case_when(
        ind_total_hit == "Bet Under" & actual_total < total_line ~ 1,
        ind_total_hit == "Bet Over" & actual_total > total_line ~ 1,
        ind_total_hit == "Bet Under" & actual_total == total_line ~ NA,
        ind_total_hit == "Bet Over" & actual_total == total_line ~ NA,
        .default = 0
      ),
    week = as.integer(str_remove(str_extract(game_id, "^2025_[0-9]+"), "^[0-9]+_"))
  ) %>% 
  left_join(df_qb_cont_old %>% select(game_id, week, qb_cont), by = c("game_id", "week")) %>% 
  group_by(game_id) %>% 
  filter(sum(qb_cont) == 2) %>% 
  ungroup() %>% 
  distinct()

df_spreads_hit_rate =
  df_total_team_test_solo_boot_prior %>% 
  left_join(
    df_total_team_test_solo_boot_prior %>% 
      group_by(game_id) %>% 
      mutate(
        team_opp = 
          case_when(
            row_number() == 1 ~ lead(team),
            row_number() == 2 ~ lag(team),
            .default = NA
          )
      ) %>% 
      relocate(team_opp, .after = team) %>% 
      ungroup() %>% 
      select(game_id, week, team_opp, starts_with("prior_"), qb_cont, rest_days, travel_km) %>% 
      rename_with(~ str_c(., "_opp"), everything() & -c(game_id, team_opp, week)) %>% 
      rename(team = team_opp),
    by = c("game_id", "team", "week")
  ) %>% 
  left_join(df_total_team_pred_bands_prior, by = c("week", "team")) %>%
  left_join(df_team_total_spread_rolling %>% select(game_id, week, team, total_team), by = c("week", "team", "game_id")) %>% 
  select(week, game_id, total_team, starts_with("prior_"), qb_cont, qb_cont_opp, rest_days, rest_days_opp, travel_km, travel_km_opp, pred_upper, pred_lower) %>% 
  drop_na() %>% 
  mutate(
    pred_total_team = predict(mod_total_team_svm, newdata = .)
  ) %>% 
  group_by(game_id) %>% 
  summarise(
    pred_spread = pred_total_team - lead(pred_total_team),
    pred_spread_upper = pred_upper - lead(pred_lower),
    pred_spread_lower = pred_lower - lead(pred_upper),
    actual_spread = total_team - lead(total_team)
  ) %>% 
  left_join(df_field_game, by = c("game_id")) %>% 
  select(game_id, ends_with("_field"), division_game, wind, temp, actual_spread, pred_spread, pred_spread_upper, pred_spread_lower) %>% 
  drop_na() %>% 
  ungroup() %>% 
  mutate(
    pred_spread_adj = predict(mod_spread_correct_enet, newdata = .)
  ) %>% 
  # left_join(df_szn_pbp %>% distinct(game_id, spread_line), by = "game_id") %>% 
  left_join(df_lines_open %>% distinct(game_id, spread_line), by = "game_id") %>% 
  mutate(
    across(c(pred_spread, pred_spread_upper, pred_spread_lower), ~ . + pred_spread_adj, .names = "{col}_adj"),
    ind_spread_hit = 
      case_when(
        spread_line > pred_spread_upper_adj ~ "Bet Away",
        spread_line < pred_spread_lower_adj ~ "Bet Home",
        .default = "No Bet"
      )
  ) %>% 
  filter(ind_spread_hit != "No Bet") %>% 
  mutate(
    ind_bet_hit = 
      case_when(
        ind_spread_hit == "Bet Away" & actual_spread < spread_line ~ 1,
        ind_spread_hit == "Bet Home" & actual_spread > spread_line ~ 1,
        ind_spread_hit == "Bet Away" & actual_spread == spread_line ~ NA,
        ind_spread_hit == "Bet Home" & actual_spread == spread_line ~ NA,
        .default = 0
      ),
    week = as.integer(str_remove(str_extract(game_id, "^2025_[0-9]+"), "^[0-9]+_"))
  ) %>% 
  left_join(df_qb_cont_old %>% select(game_id, week, qb_cont), by = c("game_id", "week")) %>% 
  group_by(game_id) %>% 
  filter(sum(qb_cont) == 2) %>% 
  ungroup() %>% 
  distinct()

df_totals_hit_rate %>% 
  # filter(qb_cont == 1) %>% 
  group_by(week) %>% 
  summarise(
    n_hit_tot = sum(ind_bet_hit),
    n_total_tot = n(),
    hit_rate_tot = round(n_hit_tot / n_total_tot * 100, 0)
  ) %>% 
  left_join(
    df_spreads_hit_rate %>% 
      # filter(qb_cont == 1) %>% 
      group_by(week) %>% 
      summarise(
        n_hit_spread = sum(ind_bet_hit),
        n_total_spread = n(),
        hit_rate_spread = round(n_hit_spread / n_total_spread * 100, 0)
      ),
    by = "week"
  ) %>% 
  mutate(
    week = as.character(week),
    n_hit_ovr = n_hit_tot + n_hit_spread,
    n_total_ovr = n_total_tot + n_total_spread,
    hit_rate_ovr = round(n_hit_ovr / n_total_ovr * 100, 0)
  ) %>% 
  rows_insert(
    tibble(
      week = "Season",
      n_hit_tot = sum(.$n_hit_tot),
      n_hit_spread = sum(.$n_hit_spread),
      n_hit_ovr = sum(.$n_hit_ovr),
      n_total_tot = sum(.$n_total_tot),
      n_total_spread = sum(.$n_total_spread),
      n_total_ovr = sum(.$n_total_ovr)
    )
  ) %>% 
  mutate(
    hit_rate_tot = 
      case_when(
        is.na(hit_rate_tot) ~ round(n_hit_tot / n_total_tot * 100, 0),
        .default = hit_rate_tot
      ),
    hit_rate_spread = 
      case_when(
        is.na(hit_rate_spread) ~ round(n_hit_spread / n_total_spread * 100, 0),
        .default = hit_rate_spread
      ),
    hit_rate_ovr = 
      case_when(
        is.na(hit_rate_ovr) ~ round(n_hit_ovr / n_total_ovr * 100, 0),
        .default = hit_rate_ovr
      ),
    hit_rate_totals = str_c(n_hit_tot, "/", n_total_tot, " (", hit_rate_tot, "%)"),
    hit_rate_spreads = str_c(n_hit_spread, "/", n_total_spread, " (", hit_rate_spread, "%)"),
    hit_rate_all = str_c(n_hit_ovr, "/", n_total_ovr, " (", hit_rate_ovr, "%)")
  ) %>% 
  select(week, hit_rate_totals, hit_rate_spreads, hit_rate_all) %>% 
  labelled::set_variable_labels(
    week = "Week",
    hit_rate_totals = "Totals",
    hit_rate_spreads = "Spreads",
    hit_rate_all = "Overall"
  ) %>% 
  gtreg::tbl_listing() %>% 
  gtsummary::modify_caption("**Hit Rates by Week**")

df_totals_hit_rate %>% 
  group_by(week, ind_total_hit) %>% 
  summarise(
    n_hit = sum(ind_bet_hit),
    n_total = n(),
    hit_rate = round(n_hit / n_total * 100, 0)
  ) %>% 
  pivot_wider(
    id_cols = week,
    names_from = ind_total_hit,
    values_from = c(n_hit, n_total, hit_rate)
  ) %>% 
  rename_with(~ str_remove(., "Bet "), everything()) %>% 
  janitor::clean_names() %>% 
  mutate(week = as.character(week)) %>% 
  rows_insert(
    tibble(
      week = "Season",
      n_hit_under = sum(.$n_hit_under, na.rm = T),
      n_hit_over = sum(.$n_hit_over, na.rm = T),
      n_total_under = sum(.$n_total_under, na.rm = T),
      n_total_over = sum(.$n_total_over, na.rm = T)
    )
  ) %>% 
  mutate(
    across(starts_with("n_"), ~ replace_na(., 0)),
    hit_rate_under = 
      case_when(
        is.na(hit_rate_under) ~ round(n_hit_under / n_total_under * 100, 0),
        .default = hit_rate_under
      ),
    hit_rate_over = 
      case_when(
        is.na(hit_rate_over) ~ round(n_hit_over / n_total_over * 100, 0),
        .default = hit_rate_over
      ),
    hit_rate_totals = str_c(n_hit_under + n_hit_over, "/", n_total_under + n_total_over, " (", round((n_hit_under + n_hit_over) / (n_total_under + n_total_over) * 100, 0), "%)"),
    hit_rate_totals_under = str_c(n_hit_under, "/", n_total_under, " (", hit_rate_under, "%)"),
    hit_rate_totals_over = str_c(n_hit_over, "/", n_total_over, " (", hit_rate_over, "%)")
  ) %>% 
  ungroup() %>% 
  select(week, starts_with("hit_rate_totals")) %>% 
  relocate(hit_rate_totals, .after = last_col()) %>% 
  labelled::set_variable_labels(
    week = "Week",
    hit_rate_totals = "Totals",
    hit_rate_totals_under = "Under Bets",
    hit_rate_totals_over = "Over Bets"
  ) %>% 
  gtreg::tbl_listing() %>% 
  gtsummary::modify_caption("**Betting Totals by Week**")

df_spreads_hit_rate %>% 
  group_by(week, ind_spread_hit) %>% 
  summarise(
    n_hit = sum(ind_bet_hit),
    n_total = n(),
    hit_rate = round(n_hit / n_total * 100, 0)
  ) %>% 
  pivot_wider(
    id_cols = week,
    names_from = ind_spread_hit,
    values_from = c(n_hit, n_total, hit_rate)
  ) %>% 
  rename_with(~ str_remove(., "Bet "), everything()) %>% 
  janitor::clean_names() %>% 
  mutate(
    across(everything(), ~ replace_na(., 0)),
    week = as.character(week)
  ) %>% 
  rows_insert(
    tibble(
      week = "Season",
      n_hit_home = sum(.$n_hit_home, na.rm = T),
      n_hit_away = sum(.$n_hit_away, na.rm = T),
      n_total_home = sum(.$n_total_home, na.rm = T),
      n_total_away = sum(.$n_total_away, na.rm = T)
    )
  ) %>% 
  mutate(
    hit_rate_home = 
      case_when(
        is.na(hit_rate_home) ~ round(n_hit_home / n_total_home * 100, 0),
        .default = hit_rate_home
      ), 
    hit_rate_away = 
      case_when(
        is.na(hit_rate_away) ~ round(n_hit_away / n_total_away * 100, 0),
        .default = hit_rate_away
      ),
    hit_rate_spreads = str_c(n_hit_away + n_hit_home, "/", n_total_away + n_total_home, " (", round((n_hit_away + n_hit_home) / (n_total_away + n_total_home) * 100, 0), "%)"),
    hit_rate_spreads_away = str_c(n_hit_away, "/", n_total_away, " (", hit_rate_away, "%)"),
    hit_rate_spreads_home = str_c(n_hit_home, "/", n_total_home, " (", hit_rate_home, "%)")
  ) %>% 
  ungroup() %>% 
  select(week, starts_with("hit_rate_spreads")) %>% 
  relocate(hit_rate_spreads, .after = last_col()) %>% 
  labelled::set_variable_labels(
    week = "Week",
    hit_rate_spreads = "Spreads",
    hit_rate_spreads_away = "Away Bets",
    hit_rate_spreads_home = "Home Bets"
  ) %>% 
  gtreg::tbl_listing() %>% 
  gtsummary::modify_caption("**Betting Spreads by Week**")
```

:::

## **Totals & Spreads of Teams Thus Far (Up to Week `r week_n - 1`)**

```{r spreads totals data clean}
#| include: false

df_spreads = 
  df_szn_pbp %>% 
  distinct(game_id, .keep_all = T) %>% 
  select(week, game_id, posteam, home_team, away_team, spread_line, result) %>% 
  pivot_longer(
    c(home_team, away_team),
    values_to = "team",
    names_to = "home_away",
    names_pattern = "(.*)_team"
  ) %>% 
  mutate(spread = ifelse(home_away == "home", spread_line, -spread_line),
         result = ifelse(home_away == "home", result, -result),
         dif = result - spread) %>% 
  select(week, team, spread, result, dif)

df_med_spread = 
  df_spreads %>% 
  group_by(team) %>% 
  summarize(med_diff = median(dif)) %>% 
  arrange(med_diff)

df_spreads = 
  df_spreads %>% 
  left_join(df_med_spread)

df_spread_cols = 
  teams_colors_logos %>% 
  mutate(team = team_abbr) %>% 
  left_join(df_med_spread) %>% 
  mutate(team = fct_reorder(as.factor(team), med_diff)) %>% 
  arrange(med_diff)

df_totals = 
  df_szn_pbp %>% 
  distinct(game_id, .keep_all = T) %>% 
  select(game_id, week, posteam, home_team, away_team, total_line, total, result) %>% 
  pivot_longer(
    c(home_team, away_team),
    values_to = "team",
    names_to = "home_away",
    names_pattern = "(.*)_team"
  ) %>% 
  mutate(dif = total - total_line) %>% 
  select(team, week, dif, total_line, total)

df_med_tot = 
  df_totals %>% 
  group_by(team) %>% 
  summarize(med_diff = median(dif)) %>% 
  arrange(med_diff)

df_totals = 
  df_totals %>% 
  left_join(df_med_tot)

df_tot_cols = 
  teams_colors_logos %>% 
  mutate(team = team_abbr) %>% 
  left_join(df_med_tot) %>% 
  mutate(team = fct_reorder(as.factor(team), med_diff)) %>% 
  arrange(med_diff)
```

::: panel-tabset

### **Spreads/Totals Boxplots**

```{r spreads totals boxplots}
plot_spreads = 
  df_spreads %>% 
  mutate(team = fct_reorder(as.factor(team), med_diff)) %>% 
  ggplot(aes(x = dif, y = team)) +
  geom_boxplot(fill = df_spread_cols$team_color, alpha = 0.75) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black") +
  labs(
    title = glue::glue("Game Results vs Spread Line"), 
    x = "Point Difference (Result - Spread)", 
    y = "Team"
  ) + 
  theme(plot.title = element_text(hjust = 0.5))

plot_totals = 
  df_totals %>% 
  mutate(team = fct_reorder(as.factor(team), med_diff)) %>% 
  ggplot(aes(x = dif, y = team)) +
  geom_boxplot(fill = df_tot_cols$team_color, alpha = 0.75) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black") +
  labs(
    title = glue::glue("Game Totals vs O/U Line"),
    x = "Point Difference (Total - Line)", 
    y = "Team") +
  theme(plot.title = element_text(hjust = 0.5))

plot_spreads + plot_totals
```

### **Spreads by Week**

```{r spreads by week}
#| fig-width: 11
#| fig-height: 8

df_spreads %>% 
  # filter(between(week, 1, 7)) %>% 
  ggplot(aes(x = week, y = dif, color = team)) + 
  # geom_line(linewidth = 1.2) + 
  geom_point(size = 3) + 
  geom_smooth(aes(group = team), se = F, method = "loess") + 
  geom_abline(slope = 0, intercept = 0, linetype = "dotted") + 
  geom_abline(slope = 0, intercept = c(-7, 7), linetype = "dashed") + 
  scale_color_manual(values = teams_colors_logos$team_color) + 
  scale_x_continuous(breaks = seq(0, 18, by = 2)) +
  coord_cartesian(ylim = c(-21, 21)) +
  facet_wrap(~ team, nrow = 4) +
  labs(
    title = "Results vs Spreads",
    x = "Week",
    y = "Point Difference (Result - Spread)"
  ) +
  theme(legend.position = "none")
```

### **Totals by Week**

```{r totals by week}
#| fig-width: 11
#| fig-height: 8

df_totals %>% 
  # filter(between(week, 1, 7)) %>% 
  ggplot(aes(x = week, y = dif, color = team)) + 
  # geom_line(linewidth = 1.2) + 
  geom_point(size = 3) + 
  geom_smooth(aes(group = team), se = F, method = "loess") + 
  geom_abline(slope = 0, intercept = 0, linetype = "dotted") + 
  geom_abline(slope = 0, intercept = c(-7, 7), linetype = "dashed") + 
  scale_color_manual(values = teams_colors_logos$team_color) + 
  scale_x_continuous(breaks = seq(0, 18, by = 2)) +
  coord_cartesian(ylim = c(-21, 21)) +
  facet_wrap(~ team, nrow = 4) +
  labs(
    title = "Totals vs Lines",
    x = "Week",
    y = "Point Difference (Total - O/U Line)"
  ) + 
  theme(legend.position = "none")
```

:::
